/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Book } from './types';

export const PROTESTANT_BOOKS: Book[] = [
  // Antigo Testamento
  { id: 'gn', name: 'Gênesis', api_id: 'Genesis', chapters: 50, testament: 'Antigo' },
  { id: 'ex', name: 'Êxodo', api_id: 'Exodus', chapters: 40, testament: 'Antigo' },
  { id: 'lv', name: 'Levítico', api_id: 'Leviticus', chapters: 27, testament: 'Antigo' },
  { id: 'nm', name: 'Números', api_id: 'Numbers', chapters: 36, testament: 'Antigo' },
  { id: 'dt', name: 'Deuteronômio', api_id: 'Deuteronomy', chapters: 34, testament: 'Antigo' },
  { id: 'js', name: 'Josué', api_id: 'Joshua', chapters: 24, testament: 'Antigo' },
  { id: 'jz', name: 'Juízes', api_id: 'Judges', chapters: 21, testament: 'Antigo' },
  { id: 'rt', name: 'Rute', api_id: 'Ruth', chapters: 4, testament: 'Antigo' },
  { id: '1sm', name: '1 Samuel', api_id: '1 Samuel', chapters: 31, testament: 'Antigo' },
  { id: '2sm', name: '2 Samuel', api_id: '2 Samuel', chapters: 24, testament: 'Antigo' },
  { id: '1rs', name: '1 Reis', api_id: '1 Kings', chapters: 22, testament: 'Antigo' },
  { id: '2rs', name: '2 Reis', api_id: '2 Kings', chapters: 25, testament: 'Antigo' },
  { id: '1cr', name: '1 Crônicas', api_id: '1 Chronicles', chapters: 29, testament: 'Antigo' },
  { id: '2cr', name: '2 Crônicas', api_id: '2 Chronicles', chapters: 36, testament: 'Antigo' },
  { id: 'ed', name: 'Esdras', api_id: 'Ezra', chapters: 10, testament: 'Antigo' },
  { id: 'ne', name: 'Neemias', api_id: 'Nehemiah', chapters: 13, testament: 'Antigo' },
  { id: 'et', name: 'Ester', api_id: 'Esther', chapters: 10, testament: 'Antigo' },
  { id: 'jo', name: 'Jó', api_id: 'Job', chapters: 42, testament: 'Antigo' },
  { id: 'sl', name: 'Salmos', api_id: 'Psalms', chapters: 150, testament: 'Antigo' },
  { id: 'pv', name: 'Provérbios', api_id: 'Proverbs', chapters: 31, testament: 'Antigo' },
  { id: 'ec', name: 'Eclesiastes', api_id: 'Ecclesiastes', chapters: 12, testament: 'Antigo' },
  { id: 'ct', name: 'Cantares', api_id: 'Song of Solomon', chapters: 8, testament: 'Antigo' },
  { id: 'is', name: 'Isaías', api_id: 'Isaiah', chapters: 66, testament: 'Antigo' },
  { id: 'jr', name: 'Jeremias', api_id: 'Jeremiah', chapters: 52, testament: 'Antigo' },
  { id: 'lm', name: 'Lamentações', api_id: 'Lamentations', chapters: 5, testament: 'Antigo' },
  { id: 'ez', name: 'Ezequiel', api_id: 'Ezekiel', chapters: 48, testament: 'Antigo' },
  { id: 'dn', name: 'Daniel', api_id: 'Daniel', chapters: 12, testament: 'Antigo' },
  { id: 'os', name: 'Oseias', api_id: 'Hosea', chapters: 14, testament: 'Antigo' },
  { id: 'jl', name: 'Joel', api_id: 'Joel', chapters: 3, testament: 'Antigo' },
  { id: 'am', name: 'Amós', api_id: 'Amos', chapters: 9, testament: 'Antigo' },
  { id: 'ob', name: 'Obadias', api_id: 'Obadiah', chapters: 1, testament: 'Antigo' },
  { id: 'jn', name: 'Jonas', api_id: 'Jonah', chapters: 4, testament: 'Antigo' },
  { id: 'mq', name: 'Miqueias', api_id: 'Micah', chapters: 7, testament: 'Antigo' },
  { id: 'na', name: 'Naum', api_id: 'Nahum', chapters: 3, testament: 'Antigo' },
  { id: 'hc', name: 'Habacuque', api_id: 'Habakkuk', chapters: 3, testament: 'Antigo' },
  { id: 'ze', name: 'Sofonias', api_id: 'Zephaniah', chapters: 3, testament: 'Antigo' },
  { id: 'ag', name: 'Ageu', api_id: 'Haggai', chapters: 2, testament: 'Antigo' },
  { id: 'zc', name: 'Zacarias', api_id: 'Zechariah', chapters: 14, testament: 'Antigo' },
  { id: 'ml', name: 'Malaquias', api_id: 'Malachi', chapters: 4, testament: 'Antigo' },

  // Novo Testamento
  { id: 'mt', name: 'Mateus', api_id: 'Matthew', chapters: 28, testament: 'Novo' },
  { id: 'mc', name: 'Marcos', api_id: 'Mark', chapters: 16, testament: 'Novo' },
  { id: 'lc', name: 'Lucas', api_id: 'Luke', chapters: 24, testament: 'Novo' },
  { id: 'joao', name: 'João', api_id: 'John', chapters: 21, testament: 'Novo' },
  { id: 'at', name: 'Atos', api_id: 'Acts', chapters: 28, testament: 'Novo' },
  { id: 'rm', name: 'Romanos', api_id: 'Romans', chapters: 16, testament: 'Novo' },
  { id: '1co', name: '1 Coríntios', api_id: '1 Corinthians', chapters: 16, testament: 'Novo' },
  { id: '2co', name: '2 Coríntios', api_id: '2 Corinthians', chapters: 13, testament: 'Novo' },
  { id: 'gl', name: 'Gálatas', api_id: 'Galatians', chapters: 6, testament: 'Novo' },
  { id: 'ef', name: 'Efésios', api_id: 'Ephesians', chapters: 6, testament: 'Novo' },
  { id: 'fp', name: 'Filipenses', api_id: 'Philippians', chapters: 4, testament: 'Novo' },
  { id: 'cl', name: 'Colossenses', api_id: 'Colossians', chapters: 4, testament: 'Novo' },
  { id: '1ts', name: '1 Tessalonicenses', api_id: '1 Thessalonians', chapters: 5, testament: 'Novo' },
  { id: '2ts', name: '2 Tessalonicenses', api_id: '2 Thessalonians', chapters: 3, testament: 'Novo' },
  { id: '1tm', name: '1 Timóteo', api_id: '1 Timothy', chapters: 6, testament: 'Novo' },
  { id: '2tm', name: '2 Timóteo', api_id: '2 Timothy', chapters: 4, testament: 'Novo' },
  { id: 'tt', name: 'Tito', api_id: 'Titus', chapters: 3, testament: 'Novo' },
  { id: 'fm', name: 'Filemom', api_id: 'Philemon', chapters: 1, testament: 'Novo' },
  { id: 'hb', name: 'Hebreus', api_id: 'Hebrews', chapters: 13, testament: 'Novo' },
  { id: 'tg', name: 'Tiago', api_id: 'James', chapters: 5, testament: 'Novo' },
  { id: '1pe', name: '1 Pedro', api_id: '1 Peter', chapters: 5, testament: 'Novo' },
  { id: '2pe', name: '2 Pedro', api_id: '2 Peter', chapters: 3, testament: 'Novo' },
  { id: '1jo', name: '1 João', api_id: '1 John', chapters: 5, testament: 'Novo' },
  { id: '2jo', name: '2 João', api_id: '2 John', chapters: 1, testament: 'Novo' },
  { id: '3jo', name: '3 João', api_id: '3 John', chapters: 1, testament: 'Novo' },
  { id: 'jd', name: 'Judas', api_id: 'Jude', chapters: 1, testament: 'Novo' },
  { id: 'ap', name: 'Apocalipse', api_id: 'Revelation', chapters: 22, testament: 'Novo' },
];
